# NumPy

Numpy is faster than Python lists. 
Numpy uses fixed type.
Eg., 5 (00000101) is stored in Numpy as an int 32-bit value in binary format. <br>
Lists used built-in int type in Python which consists of - Object Value, Object Type, Reference Count (no. of times it has been pointed to) and size. Hence, they requires a lot more space than numpy.
Therefore, Numpy is faster to read because:<br>
<li> It is faster to read less bytes of memory. </li>
<li> No type checking when iterating through objects. </li>
<li> It utilises contiguous memory. </li>
<li> Effective cache utilisation. </li>

In [1]:
import numpy as np 

In [2]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get Dimensions of the numpy array
a.ndim

1

In [5]:
# Get Shape of the array
b.shape

(2, 3)

In [6]:
# Get Type (for memory size determination)
a.dtype

dtype('int32')

In [7]:
# Get Size
a.itemsize

4

In [8]:
# Get total size
a.nbytes

12

In [35]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [9]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
# Get a specific element [r, c]
print(a[1, 5]) 
print(a[1, -2]) # -2 implies the second last column

13
13


In [13]:
# Get a specific row 
a[0, :] # Get an entire row

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
# Get a specific column
a[:, 2] # Get an entire column

array([ 3, 10])

In [15]:
# array[startindex:endindex:stepsize]
print(a[0, 1:6:2])
print(a[0, 1:-1:2])

[2 4 6]
[2 4 6]


In [16]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [24]:
a[1,5] = 20 # Original value 13

a[:,2] = [1,2] # Original Value [3, 10]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [20]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
print(b.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [19]:
# Get specific element (work outside in)
b[0,1,1]

4

In [22]:
print(b[:, 1, :])
print(b[:, 1, :].shape)

[[3 4]
 [7 8]]
(2, 2)


In [24]:
# replace 
print([[9,9,9],[8,8]])
b[:,1,:] = [[9,9,9],[8,8]] # the array shape is different 


[[9, 9, 9], [8, 8]]


ValueError: setting an array element with a sequence.

In [25]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### Initializing Different Types of Arrays

In [26]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [28]:
# Any other number
np.full((2,2), 99) # A 2x2 matrix full of 99(float32)

array([[99, 99],
       [99, 99]])

In [29]:
# Any other number (full_like)
np.full_like(a, 4) # Use the shape of array a to build an array full of 4s

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [31]:
# Random decimal numbers
np.random.rand(4,2) # can also use np.random.random_sample(a.shape)

array([[0.9110711 , 0.10580065],
       [0.21415484, 0.97602993],
       [0.50473894, 0.05203289],
       [0.04132061, 0.79308602]])

In [32]:
# Random Integer values
np.random.randint(-4,8, size=(3,3)) # Random integer values between -4 and 8

array([[-4, -4, -1],
       [-2,  7,  6],
       [ 5,  1, -4]])

In [36]:
# The identity matrix
np.identity(5) # can also mention dtype eg.'int32'

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0) 
# A 2-dimensional array has two corresponding axes: the first running vertically downwards across rows (axis 0), 
# and the second running horizontally across columns (axis 1).
r2 = np.repeat(arr,3, axis=1)
print(r1)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


In [39]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z # Using 4 instead of -1 will give the same result 
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [42]:
a = np.array([1,2,3]) 
# b = a if this is used, any changes in b will be reflected in a. b is pointing to a
b = a.copy() # This can be used to copy the array 
b[0] = 100

print(a) 
print(b)

[1 2 3]
[100   2   3]


### Mathematics

In [48]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [49]:
a + 2 # Add 2 to each element

array([3, 4, 5, 6])

In [50]:
a - 2

array([-1,  0,  1,  2])

In [51]:
a * 2

array([2, 4, 6, 8])

In [52]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [53]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [54]:
a ** 2 # Square each element of a

array([ 1,  4,  9, 16], dtype=int32)

In [56]:
# Take the sin, cos, tan
print(np.sin(a), np.cos(a), np.tan(a), sep="\n")

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


In [57]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [58]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b) # Matrix Multiplication of a and b

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [59]:
# Find the determinant

c = np.identity(3)
np.linalg.det(c)

1.0

In [60]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [61]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
np.min(stats) # Min of the array

1

In [64]:
np.max(stats)

6

In [65]:
np.max(stats, axis=1) # Max values of each rows

array([3, 6])

In [68]:
np.max(stats, axis=0)

array([4, 5, 6])

In [69]:
np.sum(stats, axis=0) # sum of all values column-wise

array([5, 7, 9])

### Reorganizing Arrays

In [71]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

after = before.reshape((1,8))
print(after)

after = before.reshape((4,2))
print(after)

after = before.reshape((2,4))
print(after)

after = before.reshape((2,2,2))
print(after)

after = before.reshape((2,3)) # Number of values must be the same
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2 3 4 5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


ValueError: cannot reshape array of size 8 into shape (2,3)

In [72]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [73]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [76]:
filedata = np.genfromtxt('data.txt', delimiter=',') # delimiter is the separator
filedata = filedata.astype('int32') # Convert to int32
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [77]:
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [78]:
filedata<100

array([[ True,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [79]:
filedata[filedata>50] # Get the values the are greater that 50

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [81]:
# Indexing with a list in NumPy

a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [83]:
np.any(filedata>50, axis=0) # What columns have values graater than 50

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [84]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [85]:
(~((filedata > 50) & (filedata < 100))) 

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

## Exercise 

In [97]:
x=np.array(range(1, 31)).reshape(6,5)
print(x)
x[2:4, 0:2]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


array([[11, 12],
       [16, 17]])

In [105]:
l = []
for i in range(4):
    l.append(x[i, i+1])    
l=np.array(l)
print(l)

[ 2  8 14 20]


In [107]:
x[[0,1,2,3], [1,2,3,4]] # We can select different list of values in row and columns and it will iterate over them

array([ 2,  8, 14, 20])

In [113]:
x[[0, -2, -1], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [114]:
x[[0,4,5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])